### ISSUE TITLE
修正案

### ISSUE THREAD

**Issue by suzukiyukito** [c0b21005c4/ProjExD#1]
https://github.com/c0b21005c4/ProjExD/blob/36d85677d614f391e954d36cd0e893de8128d0bb/kadai01/kiemoji.py#L77
__name_ == "__main___":
の下部分にall_moji_numのfor文を回してあげれば、定義の方でfor文と処理速度の効率が上がるので直す方がいいと感じる。

**Comment by c0b21005c4** [comment]
修正案感謝します。
ただfor文のbreakを関数内でしているため、修正には少し時間がかかります（技術的に授業内に収めることができなさそうです）。
コメント自体はもっともなことを言っているので後日修正していきたいです。
