### ISSUE TITLE
もっと拡張性を持たせた玉の飛び方にしたいなら

### ISSUE THREAD

**Issue by suzukiyukito** [c0b21005c4/ProjExD#12]
もし、球が前方向に飛んで、少しランダムに飛ばしたいなとおもったら、
任意の角度を0度に設定しておいて、そこから±30度で球が乱数的に飛んでいくにしてみたら、もっと散らばって球が飛ぶようになる
pygameのsSampleファイルのstar.pyのコード参照してみるといいかも
https://github.com/c0b21005c4/ProjExD/blob/18ce74cef94d69a6cf06304f06ea14614a03d27e/ex05/fight_kokaton.py#L128

**Comment by c0b21005c4** [comment]
私の技量ではお勧めされた方法で修正することができませんでした。
そのため、よりランダムに飛ぶように自分なりの修正をしました。
