### ISSUE TITLE
辞書に直して見やすくした方がよい

### ISSUE THREAD

**Issue by suzukiyukito** [c0b21005c4/ProjExD#5]
下のbuttonに関して、これはいくつかのグループにまとめたらより綺麗にまとめられる。
例えば、
dict = {textの文字:対応する関数}などと定義してあげることによってある程度のまとまりが付き、
かつcolumn,rowの部分ではfor文をdictと一緒に使ってあげることによって更に綺麗に直すことができると思う。
https://github.com/c0b21005c4/ProjExD/blob/7501c9001ef33a1f055f972172d240f64315827b/ex02/calc.py#L46

**Comment by c0b21005c4** [comment]
修正しました。
コードが見やすくなりました。
改善案ありがとうございます。
