### ISSUE TITLE
keyを押された時の処理について

### ISSUE THREAD

**Issue by suzukiyukito** [c0b21005c4/ProjExD#7]
keyの処理(上下左右)において次の処理が壁であった場合の処理はまとめて一括で処理をすることができます。
mz = make_maze(15,9)とした時、
if key == "Up" and mz[my-1][mx] == 0:
        cy -= 100
        my -= 1
等のように一緒に処理してあげた方がみやすいかも(0の時は、次に進む場所が床の時)
https://github.com/c0b21005c4/ProjExD/blob/fe22f7108f4aa41e7d40fed612adb637f4e64c2f/ex03/maze.py#L17

**Comment by c0b21005c4** [comment]
修正案ありがとうございます。その部分は私も気になっていました。ただ、私はゴールの値を3に設定しており、提示していただいた方法ではゴールできなくなってしまいます。一括で処理しようとすると現在より見にくくなる可能性があるため、このままにしようと思います。
