### ISSUE TITLE
可能なら

### ISSUE THREAD

**Issue by suzukiyukito** [c0b21005c4/ProjExD#9]
確率から爆弾を生成するプログラムなら、
check=Trueになるとき、
if check == True:
    爆弾を生成する関数()
で呼び出してしまうのでもよいとおもう
https://github.com/c0b21005c4/ProjExD/blob/cf2cb4756dd7ce6d9110756e3e7926e24eb2ee62/ex04/dodge_bomb.py#L19

**Comment by c0b21005c4** [comment]
修正しました

**Comment by c0b21005c4** [comment]
不要な部分があったため再度修正しました
